config/routes.rb
Rails.application.routes.draw do

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  devise_for :users

  # scope module: 'organizations', path: 'o'  do
  resources :organizations do
    resources :teams,       only: :show
  end

  resources :teams,         except: [:show, :index]
  resources :organizations, only: :show

  resources :users do
    resources :requests, only: [:show, :index]
  end

  resources :requests do
    resources :availabilities, only: [:new, :update, :destroy]
    resources :comments, only: [:create, :destroy]
    member do
      patch :update_status
    end
  end

  #CHART routes
  namespace :charts do
    get 'get_requests_for_user'
  end

  get '/profile/:id', to: "profiles#show", as: 'profiles'

  root 'welcome#index'
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  before_action :authenticate_user!
  before_action :get_user, only: [:show]

  def show
  end

  private

  def get_user
    @user = User.find(params[:id])
  end

  # when locking out users from profiles
  def verify_user
    unless @user == current_user
      flash[:error] =  "You do not have access to that profile"
      redirect_to profiles_path(current_user)
    end
  end

  def profile_user_self
    @user == current_user
  end



end

app/helpers/profiles_helper.rb
module ProfilesHelper

def labeled_divider(label, dashboard=true)

  ('<div class="col px-0 px-sm-1">
    <div class="d-flex py-2">
      <div class="col col-sm-2 pt-1 pl-0">
        <hr class="mt-1 border-2 hr-divider border border-warning">
      </div>
      <div class="text-center">
        <span class="">
        ' + label + '
        </span>' +
        ( dashboard ? "Dashboard" : '' ) +
      '</div>
      <div class="col pt-1 pr-0">
        <hr class="my-1 hr-divider border border-warning">
      </div>
    </div>
  </div>').html_safe

  ('<span></span>').html_safe

end

def all_requests_for(user, self_, type)
  if self_ # if on own profile, your tasks are requests with you as the recipient
    type == 'requested' ? user.requests.assigned : user.tasks.assigned
  else
    type == 'requested' ? user.requests.assigned.to_user(current_user) : user.tasks.assigned.from_user(current_user)
  end
end

end

app/views/profiles/_profile_requests.html.erb
<div class="col tab-content p-0" id="assignedTabContent">
  <!-- tab content -->
  <!-- REQUESTS ASSIGNED TO USER -->
  <div class="tab-pane fade" id="activeAssigned" role="tabpanel">
    <% assigned = all_requests_for(user, self_, 'assigned' ) %>
    <% assigned.active.each do |r| %>
      <%= render partial: 'requests/request', locals: { request: r, user: user } %>
    <% end %>
    <% unless assigned.active.any? %>
      <div class="text-dark card-body p-0 mb-2">
        <div class="card col bg-white rounded-0">
          <div class="rounded-0 row p-5">
            No active tasks
          </div>
        </div>
      </div>
    <% end %>
  </div>

  <div class="tab-pane fade" id="completedAssigned" role="tabpanel">
    <% assigned.completed.each do |r| %>
      <%= render partial: 'requests/request', locals: { request: r, user: user } %>
    <% end %>
    <% unless assigned.completed.any? %>
      <div class="text-dark card-body p-0 mb-2">
        <div class="card col bg-white rounded-0">
          <div class="rounded-0 row p-5">
            No completed tasks
          </div>
        </div>
      </div>
    <% end %>
  </div>

  <!-- REQUESTS USER HAS ASSIGNED -->
  <div class="tab-pane fade" id="activeRequests" role="tabpanel">
    <% requested = all_requests_for(user, self_, 'requested' ) %>
    <% requested.active.each do |r| %>
      <%= render partial: 'requests/request', locals: { request: r, user: user } %>
    <% end %>
    <% unless requested.active.any? %>
      <div class="text-dark card-body p-0 mb-2">
        <div class="card col bg-white rounded-0">
          <div class="rounded-0 row p-5">
            No active requests
          </div>
        </div>
      </div>
    <% end %>
  </div>

  <div class="tab-pane fade" id="completedRequests" role="tabpanel">
    <% requested.completed.each do |r| %>
      <%= render partial: 'requests/request', locals: { request: r, user: user } %>
    <% end %>
    <% unless requested.completed.any? %>
      <div class="text-dark card-body p-0 mb-2">
        <div class="card col bg-white rounded-0">
          <div class="rounded-0 row p-5">
            No completed requests
          </div>
        </div>
      </div>
    <% end %>
  </div>

  <!-- PERSONAL USER TODO'S -->
  <% if self_ %>
  <% todo = current_user.requests.my %>
  <div class="tab-pane fade" id="activeTodos" role="tabpanel">
    <% todo.active.each do |r| %>
      <%= render partial: 'requests/request', locals: { request: r, user: user } %>
    <% end %>
    <% unless todo.active.any? %>
      <div class="text-dark card-body p-0 mb-2">
        <div class="card col bg-white rounded-0">
          <div class="rounded-0 row p-5">
            CONGRATULATIONS!<br>All personal To-Do's removed
          </div>
        </div>
      </div>
    <% end %>
  </div>

  <div class="tab-pane fade" id="completedTodos" role="tabpanel">
    <% todo.completed.each do |r| %>
      <%= render partial: 'requests/request', locals: { request: r, user: user } %>
    <% end %>
    <% unless todo.completed.any? %>
      <div class="text-dark card-body p-0 mb-2">
        <div class="card col bg-white rounded-0">
          <div class="rounded-0 row p-5">
            CONGRATULATIONS!<br>All personal To-Do's removed
          </div>
        </div>
      </div>
    <% end %>
  </div>
  <% end %>

</div>

app/views/profiles/_profile_sidebar.html.erb
  <!-- REQUESTS ASSIGNED TO USER -->
  <% unless self_ %>
  <li class="d-flex border-bottom text-white user-name">
    <div class="flex-grow-1 text-center align-self-center"><%= user.display_name %></div>
  </li>
  <% end %>

  <li class="small pt-md-1 px-0 col-2 col-sm-12 col-md-12 float-left float-md-none">
    <div class="col text-md-center d-flex">
      <div class="col col-sm-3 col-md-5 d-flex text-center text-sm-right pl-0 pr-1 justify-content-right">
        <span class="ml-auto d-inline-block request-inbox"></span>
      </div>
      <span class="col pl-2 d-none d-sm-inline align-self-center text-left">
        <%= self_ ? "Your" : "" %> Tasks
      </span>

    </div>
  </li>
  <li class="nav-item col-5 col-sm-12 col-md-12 d-inline-block d-md-block px-0 float-left float-md-none">
    <% assigned = all_requests_for(user, self_, 'assigned' ) %>
    <a class="nav-link text-light p-1" id="active-assigned-tab" data-toggle="tab" href="#activeAssigned" data-target="#activeAssigned" role="tab" aria-controls="activeAssigned" aria-selected="false">
      <div class="d-flex px-1 px-sm-2 px-md-1">
        <span class="flex-grow-1 align-self-center">ACTIVE</span>
        <span class="badge badge-pill badge-light">
          <%= assigned.active.length %>
        </span>
      </div>
    </a>
  </li>
  <li class="nav-item col-5 col-sm-12 col-md-12 d-inline-block d-md-block px-0">
    <a class="nav-link text-light p-1" id="completed-assigned-tab" data-toggle="tab" href="#completedAssigned" data-target="#completedAssigned" role="tab" aria-controls="completedAssigned" aria-selected="false">
      <div class="d-flex px-1 px-sm-2 px-md-1">
        <span class="flex-grow-1 align-self-center">COMPLETED</span>
        <span class="badge badge-pill badge-light">
          <%= assigned.completed.length %>
        </span>
      </div>
    </a>
  </li>


  <!-- REQUESTS ASSIGNED BY USER -->
  <li class="small pt-md-1 px-0 col-2 col-sm-12 col-md-12 float-left float-md-none">
    <% requested = all_requests_for(user, self_, 'requested' ) %>
    <div class="col text-md-center d-flex">
      <div class="col col-sm-3 col-md-5 d-flex text-center text-sm-right pl-0 pr-1 justify-content-right">
        <span class="ml-auto d-inline-block request-outbox"></span>
      </div>
      <span class="col pl-2 d-none d-sm-inline align-self-center text-left">
        <%= self_ ? "Your" : "" %> Requests
      </span>
    </div>
  </li>
  <li class="nav-item col-5 col-sm-12 col-md-12 d-inline-block d-md-block px-0 float-left float-md-none">
    <a class="nav-link text-light p-1" id="active-requests-tab" data-toggle="tab" href="#activeRequests" data-target="#activeRequests" role="tab" aria-controls="activeRequests" aria-selected="false">
      <div class="d-flex px-1 px-sm-2 px-md-1">
        <span class="flex-grow-1 align-self-center">ACTIVE</span>
        <span class="badge badge-pill badge-light">
          <%= requested.active.length %>
        </span>
      </div>
    </a>
  </li>

  <li class="nav-item col-5 col-sm-12 col-md-12 d-inline-block d-md-block px-0">
    <a class="nav-link text-light p-1" id="completed-requests-tab" data-toggle="tab" href="#completedRequests" data-target="#completedRequests" role="tab" aria-controls="completedRequests" aria-selected="false">
      <div class="d-flex px-1 px-sm-2 px-md-1">
        <span class="flex-grow-1 align-self-center">COMPLETED</span>
        <span class="badge badge-pill badge-light">
          <%= requested.completed.length %>
        </span>
      </div>
    </a>
  </li>

  <% if self_ %>
  <!-- REQUESTS ASSIGNED TO SELF -->
  <li class="small pt-md-1 px-0 col-2 col-sm-12 col-md-12 float-left float-md-none">
    <% todo = current_user.requests.my %>
    <div class="col text-md-center d-flex">
      <div class="col col-sm-3 col-md-5 d-flex text-center text-sm-right pl-0 pr-1 justify-content-right">
        <span class="ml-auto d-inline-block request-todo"></span>
      </div>
      <span class="col pl-2 d-none d-sm-inline align-self-center text-left">
        Your ToDo's
      </span>
    </div>
  </li>
  <li class="nav-item col-5 col-sm-12 col-md-12 d-inline-block d-md-block px-0 float-left float-md-none">
    <a class="nav-link text-light p-1" id="active-todos-tab" data-toggle="tab" href="#activeTodos" data-target="#activeTodos" role="tab" aria-controls="activeTodos" aria-selected="false">
      <div class="d-flex px-1 px-sm-2 px-md-1">
        <span class="flex-grow-1 align-self-center">ACTIVE</span>
        <span class="badge badge-pill badge-light">
          <%= todo.active.length %>
        </span>
      </div>
    </a>
  </li>

  <li class="nav-item col-5 col-sm-12 col-md-12 d-inline-block d-md-block px-0">
    <a class="nav-link text-light p-1" id="completed-todos-tab" data-toggle="tab" href="#completedTodos" data-target="#completedTodos" role="tab" aria-controls="completedTodos" aria-selected="false">
      <div class="d-flex px-1 px-sm-2 px-md-1">
        <span class="flex-grow-1 align-self-center">COMPLETED</span>
        <span class="badge badge-pill badge-light">
          <%= todo.completed.length %>
        </span>
      </div>
    </a>
  </li>
  <% end %>

app/views/profiles/index.html.erb
profile INDEX for all users

app/views/profiles/show.html.erb
<% self_ = current_user.is_self(@user) %>
<%= labeled_divider(label = self_ ? 'Your' : @user.display_name.concat("'s")) %>
<div class="container-fluid px-1 p-sm-0 full-height position-absolute">

  <div class="d-sm-flex min-ht-100 pt-1 pt-sm-0 pb-5 pb-md-0">
    <!-- LEFT SIDEBAR -->
    <div id="left-sidebar" class="col-12 col-sm-4 col-md-3 col-lg-3 col-xl-2 mx-0 mt-md-0 px-0 bg-dark">
      <!-- STICKY TOP CONTAINER -->
      <div class="sticky-top">
          <div class="border-top-0 rounded-0">
            <!-- tab headers -->
            <ul class="nav nav-tabs mb-1 d-block text-white bg-primary-dark" id="taskTab" role="tablist" data-user-id="<%= @user.id %>">
              <%= render partial: 'profile_sidebar', locals: { self_: self_, user: @user } %>
            </ul>
          </div>
      </div>
    </div>
    <!-- MAIN CONTENT -->
        <div class="px-0 px-sm-1 px-md-0 col-12 col-sm-8 col-md-7 col-lg-7 col-xl-7">
          <div class="d-none d-sm-block px-sm-2 sticky-top py-2 bg-white">
            <div class="toggle-charts">
              <a class="btn text-dark m-0 px-1 py-0 btn-no-focus" href="#charts_view_01" id="toggle_charts_view" data-target="#charts_view_01" data-toggle="collapse" aria-expanded="true">
                <span class="button-label">hide</span> chart
              </a>
            </div>
              <div id="charts_view_01" class="charts w-100 position-relative collapse show">
                <%= render partial: 'charts/request_chart', locals: {user: @user, days: 7} %>
              </div>
          </div>
          <div id="requests-window" class="pb-2 px-0 px-md-2 pt-1 pt-md-2">
            <%= render partial: 'profile_requests', locals: { self_: self_, user: @user } %>
          </div>
        </div>
    <!-- RIGHT SIDEBAR -->
      <div id="right-sidebar" class="d-none d-sm-block col-sm-3 col-md-2 col-xl-3 px-0 border-left">

        <div class="pt-0 sticky-top">

          <div id="expring_requests" class="list-group list-group-flush">
            <%= render partial: 'charts/expiring_requests', locals: { user: @user, self_: self_, days: 7, request_type: 'requested' } %>
          </div>

          <div id="expring_tasks"  class="list-group list-group-flush">
            <%= render partial: 'charts/expiring_requests', locals: { user: @user, self_: self_, days: 7, request_type: 'assigned' } %>
          </div>

        </div>
      </div>
</div>

<div id="mobile_footer" class="col col-sm-4 col-md-3 col-xl-2 px-0 fixed-bottom text-center">
  <% recipient = self_ ? {} : {:recipient_id => params[:id]} %>
  <div class="btn-group w-100 pb-sm-2 bg-dark">

  <%= link_to organization_path(@user.team.organization), class: 'd-flex flex-grow-1 text-light justify-content-center',
      data:{ toggle: "tooltip", title:"group" } do %>
    <div class="d-flex align-self-center d-block">
      <span class="fa-stack">
      <%= icon('fas', 'users', class: 'fa-stack-2x') %>
      </span>
    </div>
  <% end %>

  <%= link_to new_request_path(:recipient_id => current_user.id),
      class: "d-flex flex-grow-1 text-light justify-content-center",
      data:{ toggle: "tooltip", title:"assign to #{current_user.display_name}" } do %>
    <div class="d-flex align-self-center d-block">
      <span class="fa-stack">
        <%= icon('fas', 'plus', class: 'fa-stack-1x') %>
        <%= icon('far', 'sticky-note', class: 'fa-stack-2x') %>
      </span>
    </div>
  <% end %>

  <%= link_to new_request_path(recipient),
      class: "text-light rounded-0 px-0 btn-wrap py-0",
      data:{ toggle: "tooltip", title:"assign to #{@user.display_name}" } do %>
  <div class="small flex-grow-1">
    <div class="btn-circle d-flex align-items-center justify-content-center bg-white text-dark h3 mb-0 border border-primary-dark">
      <span class="fa-stack fa-2x">
        <%= icon('fas', 'plus', class: 'fa-stack-1x') %>
      </span>
    </div>
  </div>
  <% end %>

  <%= link_to profiles_path(current_user),
      class: 'd-flex flex-grow-1 text-light justify-content-center' do %>
  <div class="d-flex align-self-center d-block">
    <span class="fa-stack">
      <%= icon('fas', 'user', class: 'fa-stack-2x') %>
    </span>
  </div>
  <% end %>

  <%= link_to edit_user_registration_path,
      class: 'd-flex flex-grow-1 text-light justify-content-center' do %>
    <div class="d-flex align-self-center d-block">
      <span class="fa-stack">
        <%= icon('fas', 'cog', class: 'fa-stack-2x') %>
      </span>
    </div>
  <% end %>

  </div>
</div>
</div>