config/routes.rb
Rails.application.routes.draw do

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  devise_for :users

  # scope module: 'organizations', path: 'o'  do
  resources :organizations do
    resources :teams,       only: :show
  end

  resources :teams,         except: [:show, :index]
  resources :organizations, only: :show

  resources :users do
    resources :requests, only: [:show, :index]
  end

  resources :requests do
    resources :availabilities, only: [:new, :update, :destroy]
    resources :comments, only: [:create, :destroy]
    member do
      patch :update_status
    end
  end

  #CHART routes
  namespace :charts do
    get 'get_requests_for_user'
  end

  get '/profile/:id', to: "profiles#show", as: 'profiles'

  root 'welcome#index'
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :request


  validates_presence_of :content
  validates_length_of :content, within: 1..100, message: "comment must be between 10 and 100 characters"

  default_scope { order(created_at: :asc) }
  
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :get_request

  def create
    @comment = @request.comments.build(comment_params)
    @comment.user_id = current_user.id

      if @comment.save
        respond_to do |format|
          format.js
          format.html {
            redirect_to @request
          }
        end
      else
        respond_to do |format|
          format.js
          format.html {
            @comment.errors.full_messages
            flash[:notice] = "Something went wrong, please try again."
            redirect_to @request
          }
        end
      end
  end

  def destroy
    @comment = Comment.find(params[:id])

    puts "destroy: "
    puts params[:id]

    if current_user == @comment.user && @comment.destroy
      respond_to do |format|
        format.js
        format.html {
          redirect_to @request
        }
      end
    else
      respond_to do |format|
        format.js
        format.html {
          flash[:alert] = "There was an error, please try again"
        }
      end
    end
  end

  private

  def get_request
    @request = Request.find(params[:request_id])
  end

  def comment_params
    params.require(:comment).permit(:content)
  end

end

app/helpers/comments_helper.rb
module CommentsHelper

  def comment_bubble(comment, left=true)
    ().html_safe
  end
  

end

app/views/comments/_comment.html.erb
<div class="list-group-item p-0" id="comment_<%= comment.id %>" >
  <div class="input-group">
    <div class="form-control border-0 <%= 'user-comment' if current_user==comment.user %>">
      <span class="d-block">
        <%= comment.content %>
      </span>
      <% if comment.user != current_user %>
        <span class="d-block text-muted small text-right">
          <%= comment.user.display_name %> - <%= time_ago_in_words(comment.created_at) %> ago
        </span>
      <% end %>
    </div>
    <div class="input-group-append p-0 ml-auto flex-shrink-1">
    <% if comment.user == current_user %>
        <%= link_to request_comment_path(comment.request, comment), method: :delete, data: { confirm: "Are you sure?", comment_id: "#{comment.id}" }, class: 'btn m-0', title: "delete?", remote: true do %>
          <%= icon('fas', 'times', class: 'text-danger')  %>
        <% end %>
    <% end %>
    </div>
  </div>
</div>

app/views/comments/_comments.html.erb
<div class="list-group" id="request_<%= request.id %>_comments" >
  <% if request.comments.any? %>
    <% request.comments.each do |comment| %>
      <%= render partial: 'comments/comment', locals: {comment: comment}%>
    <% end %>
  <% else %>
   <div class="empty-comments m-3 text-center">Add a message below to start the conversation!</div>
  <% end %>
</div>

app/views/comments/create.js.erb
var comments = $('#request_<%= @request.id %>_comments')[0].parentElement;
comments.innerHTML = ("<%= j render( partial: 'comments/comments', locals: {request: @request}) %>");

app/views/comments/destroy.js.erb
var commentId = "<%= @comment.id %>";
var comments = $('#request_<%= @request.id %>_comments')[0].parentElement;
comments.innerHTML = ("<%= j render( partial: 'comments/comments', locals: {request: @request}) %>");