config/routes.rb
Rails.application.routes.draw do

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  devise_for :users

  # scope module: 'organizations', path: 'o'  do
  resources :organizations do
    resources :teams,       only: :show
  end

  resources :teams,         except: [:show, :index]
  resources :organizations, only: :show

  resources :users do
    resources :requests, only: [:show, :index]
  end

  resources :requests do
    resources :availabilities, only: [:new, :update, :destroy]
    resources :comments, only: [:create, :destroy]
    member do
      patch :update_status
    end
  end

  #CHART routes
  namespace :charts do
    get 'get_requests_for_user'
  end

  get '/profile/:id', to: "profiles#show", as: 'profiles'

  root 'welcome#index'
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  before_action :authenticate_user!, except: :index
  before_action :get_user

  def index
  end

  private

  def get_user
    @user = current_user
  end
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/welcome/index.html.erb
<div class="container-fluid mt-1 px-0">
  <div class="d-flex px-1 pb-3 p-5">
    <div class="main-content px-1 pb-5 pb-sm-1 flex-grow-1">
      <div class="d-flex">
          <div class="p-5 align-self-center">
            <h3>Welcome to EO!</h3>
            <div class="py-2">
              Your hub for managing waitlists for all of your expanding opportunities
            </div>
            <div class="button-group">
              <% unless @user %>
                <%= link_to new_user_session_path, class: 'btn btn-outline bg-primary-light text-dark' do %>
                  Log in
                <% end %>
                or
              <%= link_to new_user_registration_path, class: 'btn btn-outline bg-primary-light text-dark' do %>
                Sign Up
              <% end %>
            <% else %>
              <div>
                Start a new team now!
              </div>
            <% end %>
            </div>
          </div>
      </div>
    </div>
  </div>

  <% if @user %>
    <div id="mobile_footer" class="col col-sm-4 col-md-3 col-xl-2 d-sm-none px-0 fixed-bottom text-center">

    <div class="btn-group w-100 pb-sm-2 bg-dark">
      <%= link_to profiles_path(current_user),
      class: 'd-flex flex-grow-1 text-light justify-content-center' do %>
      <div class="d-flex align-self-center d-block">
        <span class="fa-stack">
          <%= icon('fas', 'user', class: 'fa-stack-2x') %>
        </span>
      </div>
      <% end %>

    <%= link_to new_request_path,
        class: "d-flex flex-shrink text-light justify-content-center",
        data:{ toggle: "tooltip", title:"assign to #{current_user.display_name}" } do %>
        <div class="small flex-grow-1">
          <div class="btn-circle d-flex align-items-center justify-content-center bg-white text-dark h3 mb-0 border border-primary-dark">
            <span class="fa-stack fa-2x">
              <%= icon('fas', 'plus', class: 'fa-stack-1x') %>
            </span>
          </div>
        </div>
    <% end %>

    <%= link_to edit_user_registration_path,
        class: 'd-flex flex-grow-1 text-light justify-content-center' do %>
      <div class="d-flex align-self-center d-block">
        <span class="fa-stack">
          <%= icon('fas', 'cog', class: 'fa-stack-2x') %>
        </span>
      </div>
    <% end %>
  </div>
<% end %>

  </div>
</div>