config/routes.rb
Rails.application.routes.draw do

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  devise_for :users

  # scope module: 'organizations', path: 'o'  do
  resources :organizations do
    resources :teams,       only: :show
  end

  resources :teams,         except: [:show, :index]
  resources :organizations, only: :show

  resources :users do
    resources :requests, only: [:show, :index]
  end

  resources :requests do
    resources :availabilities, only: [:new, :update, :destroy]
    resources :comments, only: [:create, :destroy]
    member do
      patch :update_status
    end
  end

  #CHART routes
  namespace :charts do
    get 'get_requests_for_user'
  end

  get '/profile/:id', to: "profiles#show", as: 'profiles'

  root 'welcome#index'
end

app/models/request.rb
class Request < ApplicationRecord
  belongs_to :user
  belongs_to :recipient, class_name: 'User'

  has_many :comments, inverse_of: :request, dependent: :destroy
  accepts_nested_attributes_for :comments, allow_destroy: true

  has_many :availabilities, inverse_of: :request, dependent: :destroy
  accepts_nested_attributes_for :availabilities, allow_destroy: true,
                                reject_if: :all_blank, limit: 4

  validates_presence_of :user_id, :recipient_id, :body
  validates_presence_of :client_name, :unless => :subject?, message: "%{value} required if no subject supplied"
  validates_presence_of :subject, :unless => :client_name?, message: "%{value} required if no client name supplied"
  validates_length_of :body, within: 10..300, message: "message body must be between 10 and 300 characters"
  validates_length_of :subject, within: 5..300,:unless => :client_name?, message: "message subject must be between 10 and 300 characters"
  validates_length_of :client_name, within: 4..40, :unless => :subject?, message: "must be longer than 2 characters"

  enum status: [:active, :completed]

  scope :most_recent, -> { order('created_at DESC' ) }
  scope :my, -> { where("user_id = recipient_id") }
  scope :assigned, -> { where("user_id != recipient_id") }
  scope :to_user, ->(user=nil) { where(recipient: user) }
  scope :from_user, ->(user=nil) { where(user: user)}

  def participants(*args)
    args.any? do |user|
      return true if self.user == user || self.recipient == user
    end
    false
  end

end

app/controllers/requests_controller.rb
class RequestsController < ApplicationController
  before_action :authenticate_user!

  before_action :get_request, only: [:show, :edit, :update, :destroy, :update_status]
  before_action :set_user, only: [:new,:create,:edit,:update, :destroy]

  def index
    @user = current_user
  end

  def show
    @recipient = @request.recipient
    @user = @request.user
    respond_to do |format|
      format.json { render json: @request }
      format.html {
          render layout: 'application'
      }
    end
  end

  def new
    @request = @user.requests.new
    @request.recipient_id = params[:recipient_id] if params[:recipient_id]
    @users = User.all
  end

  def create
    @request = @user.requests.build(request_params)
    @users = User.all

    begin
      if @request.save
        flash[:notice] = "request saved"
        redirect_to @request
      else
        flash[:alert] = "unable to process request, please try again"
        render :new
      end
    rescue ActiveRecord::NestedAttributes::TooManyRecords
      flash[:alert] = "Limit reached for availabilies"
      render :new
    end
  end

  def edit
    if @user != @request.user && @user != @request.recipient
      flash[:alert] = "you do not have appropriate permission"
      redirect_to @request
    end
  end

  def update

    begin
      if @request.update_attributes(request_params)
        flash[:notice] = "request updated"
        redirect_to @request
      else
        @request.errors.full_messages
        flash[:alert] = "unable to update request, please see errors below"
        render :edit
      end
    rescue ActiveRecord::NestedAttributes::TooManyRecords
      flash[:alert] = "Limit reached for availabilies"
      render :edit
    end
  end

  def destroy

    if (current_user == @request.user || current_user == @request.recipient) && @request.destroy
        respond_to do |format|
          format.js
          format.html {
            flash[:notice] = "request removed"
            redirect_to profiles_path(current_user)
          }
        end
    else
        respond_to do |format|
          format.js
          format.html {
            flash[:alert] = "unable to delete request"
            render :edit
          }
        end
    end
  end

  def update_status

    @request.status = @request.active? ? "completed" : "active"

    if @request.participants(current_user)

      profile_id = request.referrer.match(/profile\/\d+/) ? request.referrer.match(/profile\/(\d+)/)[1].to_i : current_user.id

      if profile_id
        @user = User.find(profile_id)
      end

      if @request.save
        respond_to do |format|
          format.js {
          }
          format.html {
            flash[:notice] = "Request status updated"
          }
        end
      else
        respond_to do |format|
          format.js {
            # render status: 422
            render status: 422
          }
          format.html {
            flash[:alert] = "unable to process"
          }
        end
      end
    else
      puts "error from non-authorized user"
      puts @request
      respond_to do |format|
        format.js { render status: 422 }
        format.html {
          flash[:alert] = "you do not have the appropriate permissions for this action."
        }
      end
    end

  end

  private

  def request_params
    params.require(:request).permit(
      :subject,:body,:status, :client_name, :user_id, :recipient_id,
      availabilities_attributes: [:id, :date, :startTime, :endTime, :endDate, :request_id, :_destroy]
    )
  end

  def set_user
    @user = current_user
  end

  def get_request
    @request = Request.find(params[:id])
  end

end

app/helpers/requests_helper.rb
module RequestsHelper

  def format_date(date,short=nil)
    return if date.nil?
    time = Date.parse(date.to_s)
    time.strftime("%-m/%-d")
  end

  def format_time(time)
    return if time.nil?
    time = Time.parse(time.to_s)
    time.strftime("%l:%M%p").sub!('M','').downcase
  end

  def format_availability(a)
    date = [] <<  if a.date || a.endDate
                    if a.endDate.nil?
                      ["on",format_date(a.date)]
                    elsif a.date.nil?
                      ["before", format_date(a.endDate)]
                    else
                      [format_date(a.date), "-", format_date(a.endDate)]
                    end
                  end

    time = [] <<  if a.startTime || a.endTime
                    if a.startTime.nil?
                      ["by", format_time(a.endTime)]
                    elsif a.endTime.nil?
                      ["after", format_time(a.startTime)]
                    else
                      [" from", format_time(a.startTime), "-", format_time(a.endTime)]
                    end
                  end

    joiner = "::" if date.count + time.count == 2
    [date,time].flatten.join(" ").html_safe
  end

end

app/views/requests/_availability_fields.html.erb
<div class="input-group no-border nested-fields">
<div class="col-12 col-sm-6 col-md-5 p-0">
  <div class="col-6 float-left px-1 mb-2">
    <small>earliest date:</small>
    <%= f.date_field :date, class: 'form-control form-control-sm no-bg', placeholder: "start date" %>
  </div>
  <div class="col-6 float-left px-1 mb-2">
    <small>latest date:</small>
    <%= f.date_field :endDate, class: 'form-control form-control-sm no-bg' %>
  </div>
</div>
<div class="col-12 col-sm-6 col-md-5 p-0">
  <div class="col-6 float-left px-1 mb-2">
    <small>start by:</small>
    <%= f.time_field :startTime, class: 'form-control form-control-sm no-bg' %>
  </div>
  <div class="col-6 float-left px-1 mb-2">
    <small>finish by:</small>
    <%= f.time_field :endTime, class: 'form-control form-control-sm no-bg' %>
  </div>
</div>

  <div class="col-12 col-md-2 text-center text-sm-right p-0 mt-md-4 mb-2">
    <%= link_to_remove_association f, { class: 'btn btn-outline-warning col-sm-3 col-md-12 px-0'} do %>
    remove <span class="d-none d-sm-inline d-md-none d-lg-inline">date/time</span>
    <% end %>
  </div>
</div>

app/views/requests/_availability_form_fields.html.erb
<div class="input-group no-border nested-fields">
<div class="col-12 col-sm-6 col-md-5 p-0">
  <div class="col-12 col-md-6 float-left px-1 mb-2">
    <small>earliest date:</small>
    <%= f.date_field :date, class: 'form-control form-control-sm', placeholder: "start date" %>
  </div>
  <div class="col-12 col-md-6  float-left px-1 mb-2">
    <small>latest date:</small>
    <%= f.date_field :endDate, class: 'form-control form-control-sm' %>
  </div>
</div>
<div class="col-12 col-sm-6 col-md-5 p-0">
  <div class="col-12 col-md-6 float-left px-1 mb-2">
    <small>start by:</small>
    <%= f.time_field :startTime, class: 'form-control form-control-sm' %>
  </div>
  <div class="col-12 col-md-6 float-left px-1 mb-2">
    <small>finish by:</small>
    <%= f.time_field :endTime, class: 'form-control form-control-sm' %>
  </div>
</div>


  <div class="col-12 col-md-2 text-center text-sm-right p-0 mt-md-4 mb-2 px-1">
    <%= link_to_remove_association f, { class: 'btn btn-outline-danger border-0 px-2'} do %>
      <%= icon('fas', 'times') %>
      remove <span class="d-sm-none">date & time</span>
    <% end %>
  </div>
</div>

app/views/requests/_availability_request.html.erb
<div class="input-group no-border">
  <div class="col-6 col-md-3">
    <%= a.date_field :date, class: 'form-control form-control-sm text-light no-bg' %>
    <small>earliest date:</small>
  </div>
  <div class="col-6 col-md-3">
    <%= a.date_field :endDate, class: 'form-control form-control-sm text-light no-bg' %>
    <small>latest date:</small>
  </div>
  <div class="col-6 col-md-3">
    <%= a.time_field :startTime, class: 'form-control form-control-sm text-light no-bg' %>
    <small>start by:</small>
  </div>
  <div class="col-6 col-md-3">
    <%= a.time_field :endTime, class: 'form-control form-control-sm text-light no-bg' %>
    <small>finish by:</small>
  </div>
  <div class="col-12 text-right">
    Delete: <%= a.check_box :_destroy %>
  </div>
  <div class="">
    <%= link_to_remove_association "-", a %>
  </div>
</div>

app/views/requests/_datetime_request.html.erb
<%= tag.div class: 'card bg-primary-dark p-1 p-sm-2 text-md-center text-white d-flex mx-1' do %>
  <%= format_availability(availability) %>
<% end %>

app/views/requests/_request.html.erb
<div class="card-body p-0 pb-1" id="request_block_<%= request.id %>">
  <div class="flex-column position-relative bg-white rounded-0 p-2 py-md-1 border">
    <div class=" bg-white rounded-0 d-flex justify-content-between">
      <div id="request_header_<%= request.id %>" class="d-sm-flex justify-content-between align-items-center w-100 py-0 py-sm-2">
          <span class="d-flex flex-grow-1"><%= request.subject %></span>
          <span class='small d-block mr-2'>
            <% if request.completed? %>
            <%= "completed " + time_ago_in_words(request.updated_at) + " ago " %>
            <% else %>
            <%= "submitted " + time_ago_in_words(request.created_at) + " ago " %>
            <% end %>

          </span>
      </div>

      <div id="request_<%= request.id %>_tools" class="request-tools align-items-sm-center">
        <%= link_to request_path(request), class: 'btn px-1 py-0 text-dark btn-lg' do %>
          <% if request.comments.any? %>
            <%= icon('fas', 'comments') %>
          <% else %>
            <%= icon('far', 'comments') %>
          <% end %>
        <% end %>

        <%= link_to edit_request_path(request), class: 'btn px-1 py-0 text-dark btn-lg' do %>
          <%= icon('fas', 'edit') %>
        <% end %>
        <a class="btn px-1 py-0 text-dark btn-lg" href="#toggle_<%= request.id %>" data-toggle="collapse" data-loading-text="open" aria-expanded="false">
          <%= icon('fas', 'info-circle', class: 'bs-toggle') %>
        </a>
      </div>

    </div>
    <div class="flex-column collapse" id="toggle_<%= request.id %>" aria-expanded="false">

        <div class="py-1 my-1 px-1 bg-light border">
          <%= tag.i request.client_name, class: "font-weight-bold" %>
          <div class="col p-0 mb-2">
           <%= simple_format request.body %>
           </div>
        </div>

          <% if request.availabilities.any? %>

              <div class="d-flex pb-1 px-0 px-sm-1">
                <div class="col-1 d-flex align-self-center p-0">
                  <hr class="mt-1 hr-divider">
                </div>
                <div class="small text-center px-1">
                  <span class="">requests</span>
                </div>
                <div class="col px-0 align-self-center">
                  <hr class="my-1 hr-divider">
                </div>
              </div>
              <div class="d-block d-md-flex">

                  <div class="d-flex">
                    <% request.availabilities.each_with_index do |a, i| %>
                      <%= render partial: 'requests/datetime_request', locals: { availability: a, index: i } %>
                    <% end %>
                  </div>

              </div>
              <div class="d-block px-0 px-sm-1">
                <div class="d-block">
                  <hr class="hr-divider">
                </div>
              </div>
            <% end %>

      <div class="d-flex mt-2 justify-content-end">
        <div class="w-50 text-left">

          <% if request.participants(current_user) %>
          <div id="request_status_<%= request.id %>" class="d-flex" data-request-status="<%= request.status %>">
            <%= link_to update_status_request_path(request), remote: true, method: :patch, class: 'text-dark nav-link p-0', data: { request: request.id } do %>
              <% if request.completed? %>

                <span class="d-flex align-items-center" title="status: completed">

                  <div class="toggle-holder bg-primary-dark">
                    <span class="toggle-circle toggle-circle-on"></span>
                  </div>
                  <span class="request-label small pl-2"><%= request.status %></span>
                </span>

              <% else %>
                <span class="d-flex align-items-center" title="status: pending">
                  <div class="toggle-holder bg-primary-dark bg-status-active">
                    <span class="toggle-circle"></span>
                  </div>
                  <span class="request-label small pl-2"><%= request.status %></span>
                </span>
              <% end %>
            <% end %>
          </div>
          <% end %>

        </div>
        <div class="w-50 text-right">
          <div class="small text-muted" >

              <% if request.user == request.recipient %>
                <span><%= icon('far', 'clipboard')%></span>
              <% else %>
                <span>assigned to <%= tag.span request.recipient.display_name, class: "text-dark" %> by <%= tag.span request.user.display_name, class: "text-dark" %></span>
              <% end %>

          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/requests/index.html.erb
<% self_ = current_user.is_self(@user) %>

  <%= labeled_divider(label = self_ ? 'Your' : @user.display_name.concat("'s")) %>

  <div class="d-md-flex mb-sm-2 mb-md-3">
    <div class="p-0 col-12 col-md-8">
      <div id="requests-window">

        <div class="d-none d-lg-inline col-6 position-absolute">
          <ul class="nav nav-tabs">
            <% if self_ %>
            <li>
                <span class="">Your Tasks</span>
            </li>
            <% else %>
            <li>
              <span class="">Tasks You've assigned to this member</span>
            </li>
            <% end %>
          </ul>
        </div>
          <div class="d-block col-sm-8 col-md-7 px-1 ml-auto ">

          <ul class="nav nav-tabs nav-justified mb-1" id="taskTab" role="tablist">

            <li class="nav-item">
              <a class="nav-link text-dark px-1 py-1 active" id="active-tasks-tab" data-toggle="tab" href="#activeTasks" role="tab" aria-controls="activetasks" aria-selected="true">
                  <div class="">
                    <% if @user.tasks.assigned.active.any? %>
                    <% end %>
                    <span class="d-block">ACTIVE</span>
                    <span class="badge badge-pill badge-dark">
                      <%= @user.tasks.assigned.active.length %>
                    </span>
                  </div>
              </a>
            </li>

            <li class="nav-item">
              <a class="nav-link text-dark px-1 py-1" id="completed-tasks-tab" data-toggle="tab" href="#completedTasks" role="tab" aria-controls="completedtasks" aria-selected="false">
                <div class="">
                  <% if @user.tasks.assigned.completed.any? %>
                  <% end %>
                  <span class="d-block">COMPLETE</span>
                  <span class="badge badge-pill badge-dark">
                    <%= @user.tasks.assigned.completed.length %>
                  </span>
                </div>
              </a>
            </li>

            <li class="nav-item">
              <a class="nav-link text-dark px-1 py-1" id="completed-todos-tab" data-toggle="tab" href="#allTodos" role="tab" aria-controls="completedtodos" aria-selected="false">
                <div class="">
                  <% if @user.tasks.my.any? %>
                  <% end %>
                  <span class="d-block">ToDo's</span>
                  <span class="badge badge-pill badge-dark">
                    <%= @user.tasks.my.length %>
                  </span>
                </div>
              </a>
            </li>

          </ul>

        </div>

        <div class="tab-content" id="taskTabContent">

          <div class="tab-pane fade show active" id="activeTasks" role="tabpanel">
            <% @user.tasks.assigned.active.each do |request| %>
              <%= render partial: 'requests/request', locals: { request: request, task: true } %>
            <% end %>
            <% unless @user.tasks.assigned.active.any? %>
              <div class="text-dark card-body p-0 p-sm-1 mb-2 mb-sm-2">
                <div class="card col bg-white rounded-0">
                  <div class="rounded-0 row p-5">
                    CONGRATULATIONS!<br>No Active requests
                  </div>
                </div>
              </div>
            <% end %>
          </div>

          <div class="tab-pane fade" id="completedTasks" role="tabpanel">
            <% @user.tasks.assigned.completed.each do |request| %>
              <%= render partial: 'requests/request', locals: { request: request, task: true } %>
            <% end %>
            <% unless @user.tasks.assigned.completed.any? %>
              <div class="text-dark card-body p-0 p-sm-1 mb-2 mb-sm-2">
                <div class="card col bg-white rounded-0">
                  <div class="rounded-0 row p-5">
                    CONGRATULATIONS!<br>All completed requests removed
                  </div>
                </div>
              </div>
            <% end %>
          </div>

          <div class="tab-pane fade" id="allTodos" role="tabpanel">
            <% @user.tasks.my.each do |request| %>
              <%= render partial: 'requests/request', locals: { request: request, task: true } %>
            <% end %>
            <% unless @user.tasks.my.completed.any? %>
              <div class="text-dark card-body p-0 p-sm-1 mb-2 mb-sm-2">
                <div class="card col bg-white rounded-0">
                  <div class="rounded-0 row p-5">
                    CONGRATULATIONS!<br>All personal To-Do's removed
                  </div>
                </div>
              </div>
            <% end %>
          </div>

        </div>
    </div>
  </div>

  <div class="d-none d-sm-block d-md-inline col-md-4 px-1 mt-5">
    <div id="profile_sidebar" class="sidebar border border-warning card">
      <div class="card-header p-2 p-md-3">
        <div class="card-title mb-sm-1">
          <%= @user.display_name %>
        </div>
      </div>
      <div class="p-2 p-lg-3">
        <div class="col-6 col-md-12 d-dm-block float-sm-left float-md-none px-0">
            <%= link_to new_request_path(:recipient_id => params[:id]), class: "rounded-0 btn text-success text-center text-md-left d-block" do %>
              <%= icon('fas', 'plus') %><span class="ml-2"><%= current_user.is_self(@user) ? 'Create a task' : 'Send a request' %></span>
            <% end %>
        </div>
        <div class="col-6 col-md-12 d-dm-block float-sm-left float-md-none px-0">
          <% if self_ %>
            <%= link_to edit_user_registration_path, class: 'rounded-0 btn text-success text-sm-center text-md-left d-block' do %>
              <%= icon('fas', 'user-cog') %><span class="ml-2">Account Settings</span>
            <% end %>
          <% end %>
        </div>
        <div class="d-flex border-top pt-2 mt-2 w-100">
          <span class="small text-muted d-block"><i>Last logged in: <%= format_date(current_user.last_sign_in_at) + " at " + format_time(current_user.last_sign_in_at) %></i></span>
        </div>
      </div>
    </div>
  </div>
</div>

<div id="sticky_footer" class="d-block d-sm-none fixed-bottom text-center">
  <% recipient = self_ ? {} : {:recipient_id => params[:id]} %>
  <div class="btn-group w-100">

  <%= link_to root_path, class: 'btn  bg-dark text-light rounded-0 border-dark px-0 w-50 btn-wrap py-2' do %>
    <div class="flex-grow-1">
      <%= icon('fas', 'users') %>
    </div>
  <% end %>

  <%= link_to new_request_path(:recipient_id => current_user.id), class: "btn bg-dark text-light rounded-0 border-dark px-0 w-50 btn-wrap py-2" do %>
    <div class="small flex-grow-1">
      <span class="fa-stack">
        <%= icon('fas', 'plus', class: 'fa-stack-1x') %>
        <%= icon('far', 'sticky-note', class: 'fa-stack-2x') %>
      </span>
    </div>
  <% end %>

  <%= link_to new_request_path(recipient), class: "btn bg-dark text-light rounded-0 border-dark px-0 w-50 btn-wrap py-2" do %>
  <div class="small flex-grow-1">
    <span class="fa-stack">
      <%= icon('fas', 'user', class: 'fa-stack-1x') %>
      <%= icon('far', 'sticky-note', class: 'fa-stack-2x') %>
    </span>
  </div>
  <% end %>

  <%= link_to edit_user_registration_path, class: 'btn  bg-dark text-light rounded-0 border-dark px-0 w-50 btn-wrap py-2' do %>
    <div class="small flex-grow-1">
      <span class="fa-stack">
        <%= icon('fas', 'user-cog', class: '') %>
      </span>
    </div>
  <% end %>

  </div>
</div>

app/views/requests/show.html.erb
<div class="container-fluid px-0 mb-5">
  <div class="request-container d-flex flex-wrap">
<!-- LEFT COLUMN -->
    <div class="request-left-column col-12 col-sm-4 col-lg-3 p-0">
      <div class="col-12 col-sm-4 col-lg-3 p-0 bg-dark text-light">
        <div class="request-card pt-2 border-bottom p-2 py-lg-3">

            <div class="request-header d-flex">
              <span class="request-subject d-inline-flex mr-auto h5"><%= @request.subject %></span>
            </div>
            <%= tag.div @request.client_name, class:'request-name col-12 p-0' %>
            <div class="request-body border border-warning p-2 mb-2 mt-1 bg-white text-dark">
              <div class="mb-2"><%= simple_format @request.body %></div>
            </div>
          <% if @request.availabilities.any? %>
            <!-- availabilities -->


            <div class="align-items-center my-1 mx-0">
              <div class="small px-2">
                requests
              </div>
            </div>

            <div class="d-flex mb-2">

                  <% @request.availabilities.each_with_index do |a, i| %>
                    <div class="m-1">
                      <%= tag.div class: 'p-1 bg-white rounded text-center text-dark' do %>
                        <%= format_availability(a) %>
                      <% end %>
                    </div>
                  <% end %>

            </div>
          <% end %>

          <!-- request footer -->
          <div class="request-card-footer">
            <div class="mb-2 d-flex">

              <div id="request_status_<%= @request.id %>" class="mr-auto" >

                <%= link_to update_status_request_path(@request), remote: true, method: :patch, class: 'text-light nav-link p-0', data:  {status: "#{@request.status}"} do %>
                  <% if @request.completed? %>

                    <span class="d-flex align-items-center" title="status: completed">

                      <div class="toggle-holder bg-primary-dark">
                        <span class="toggle-circle toggle-circle-on"></span>
                      </div>
                      <span class="request-label small pl-2"><%= @request.status %></span>
                    </span>

                  <% else %>
                    <span class="d-flex align-items-center" title="status: active">
                      <div class="toggle-holder bg-primary-dark bg-status-active">
                        <span class="toggle-circle"></span>
                      </div>
                      <span class="request-label small pl-2"><%= @request.status %></span>
                    </span>
                  <% end %>
                <% end %>

              </div>

              <% if @request.participants(current_user) %>
              <div class="d-block">
                  <%= link_to edit_request_path(@request), class: 'btn btn-outline-light btn-sm border-0', title: 'edit request' do %>
                    <%= icon('fas', 'edit') %>
                  <% end %>
                </div>
              <% end %>

            </div>
          </div>
          <!-- request footer end -->

        </div>
      </div>
    </div>
<!-- MIDDLE COLUMN -->
    <div class="request-middle-column col-12 col-sm-8 col-md-5 col-lg-6 p-0 flex-column d-flex border-right border-left">
      <div class="mb-auto"></div>
      <div class="scrollable-content">
        <%= render partial: 'comments/comments', locals: {request: @request } %>
      </div>

      <div class="comment-input p-1 bg-dark col-sm-8 offset-sm-4 col-md-5 offset-md-4 col-lg-6 offset-lg-3 fixed-bottom">
        <%= form_with model: [@request, Comment.new], html: { id: 'request_comment', data: { request: @request.id } } do |f| %>
          <div class="input-group">
            <%= f.text_field :content, placeholder: 'add-comment', class: 'form-control rounded-0 flex-grow-1', autofocus: true, autocomplete: :off %>
            <div class="input-group-append p-0 ml-auto flex-shrink-1">
              <%= f.button :button, type: :submit, class: 'btn text-light bg-dark border-0 rounded-0', id: "comment_submit" do %>
              <%= icon('fas', 'comment') %>
              <% end %>
            </div>
          </div>
        <% end %>
      </div>
      </div>

<!-- RIGHT COLUMN -->
    <div class="d-none d-md-block col-md-3 p-0">

      <div class="position-fixed d-none col-md-3 d-block p-0">
        <div class="user-mini-dash d-inline-flex w-100">

            <div class="border-bottom border-warning flex-column w-100">
              <div class="card-header p-2 px-lg-3 no-bg border-0">
                <div class="card-title mb-sm-1">
                  <% if @recipient != current_user %>
                    <%= link_to profiles_url(@recipient) do %>
                      <% @recipient.display_name %>
                    <% end %>
                  <% else %>
                    <%= @recipient.display_name %>
                  <% end %>
                </div>
              </div>
              <div class="p-2 px-lg-3">
                <div class="col-6 col-md-12 d-dm-block float-sm-left float-md-none px-0">
                    <%= link_to new_request_path(@recipient), class: "rounded-0 btn text-success text-center text-md-left d-block" do %>
                      <%= icon('fas', 'plus') %><span class="ml-2"><%= current_user.is_self(@recipient) ? 'Create a task' : 'Send a request' %></span>
                    <% end %>
                </div>
                <div class="col-6 col-md-12 d-dm-block float-sm-left float-md-none px-0">
                  <% if current_user == @recipient %>
                    <%= link_to edit_user_registration_path, class: 'rounded-0 btn text-success text-sm-center text-md-left d-block' do %>
                      <%= icon('fas', 'user-cog') %><span class="ml-2">Account<span class="d-none d-lg-inline"> Settings</span></span>
                    <% end %>
                  <% end %>
                </div>
                <div class="d-flex border-top pt-2 mt-2 w-100">
                  <span class="small text-muted d-block"><i>Last logged in: <%= format_date(current_user.last_sign_in_at) + " at " + format_time(current_user.last_sign_in_at) %></i></span>
                </div>
              </div>
            </div>

        </div>
      </div>

    </div>
  </div>

  <div class="request-footer">
  </div>

</div>

app/views/requests/update_status.js.erb
var request = {
  id: "<%= @request.id %>",
  status: '<%= @request.status %>'
}
$('#taskTab').show(function() {
  request.profile_user = $('#taskTab')[0].dataset.userId;
  request.sidebar = "<%= j (render partial: 'profiles/profile_sidebar',   locals: { self_: @user.is_self(current_user), user: @user }) %>";
  request.requests = "<%= j (render partial: 'profiles/profile_requests', locals: { self_: @user.is_self(current_user), user: @user }) %>";
});